<?xml version="1.0"?>

<robot name="sensor" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="stereo_z" value="0.05" />
  <xacro:property name="stereo_y" value="0.07" />
  <xacro:property name="stereo_x" value="0.05" />
  <xacro:property name="object_height" value="1" />

 <!-- Used for fixing robot to Gazebo 'base_link' -->
  <link name="world"/>

 <!-- Base Link -->
  <link name="sensor_link">
    <collision>
      <origin xyz="-${stereo_z/2} 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${stereo_x} ${stereo_y} ${stereo_z}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="-${stereo_x/2} 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${stereo_x} ${stereo_y} ${stereo_z}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
  </link>

  <joint name="sensor_joint" type="fixed">
    <parent link="world"/>
    <child link="sensor_link"/>
    <origin xyz="0 0 ${object_height}" rpy="0 0 0" /> 
    <!-- 0.75 0.035 0.5 -->
  </joint>


  <link name="object_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.1 0.1 0.1"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.1 0.1 0.1"/>
      </geometry>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
  </link>

  <joint name="object_joint" type="fixed">
    <parent link="world"/>
    <child link="object_link"/>
    <origin xyz="1 0 ${object_height}" rpy="0 0 0" />
  </joint>



  <link name="object2_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="0.05"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <!-- <sphere radius="0.05"/> -->
        <box size="0.1 0.1 0.1"/>
      </geometry>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
  </link>

  <joint name="object2_joint" type="fixed">
    <parent link="world"/>
    <child link="object2_link"/>
    <origin xyz="1 0.25 ${object_height}" rpy="0 0 0" />
  </joint>

  <link name="object3_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.05 0.05 0.05"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.1 0.1 0.1"/>
      </geometry>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
  </link>

  <joint name="object3_joint" type="fixed">
    <parent link="world"/>
    <child link="object3_link"/>
    <origin xyz="1 -0.25 ${object_height}" rpy="0 0 0" />
  </joint>

  <material name="orange">
    <color rgba="${255/255} ${108/255} ${10/255} 1.0"/>
  </material>
  <gazebo reference="object_link">
    <material>Gazebo/Orange</material>
  </gazebo>
  <gazebo reference="object2_link">
    <material>Gazebo/Green</material>
  </gazebo>
  <gazebo reference="object3_link">
    <material>Gazebo/Blue</material>
  </gazebo>
 <gazebo reference="sensor_link">
    <material>Gazebo/Black</material>
  </gazebo>

</robot>
