<?xml version="1.0"?>

<robot name="stereo_camera" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- camera -->
    <xacro:include filename="$(find sensor_sim_gazebo)/urdf/stereo_camera.gazebo.xacro"/>

    <xacro:property name="stereo_z" value="0.05" />
    <xacro:property name="stereo_y" value="0.07" />
    <xacro:property name="stereo_x" value="0.05" />
    <xacro:property name="object_height" value="1" />

    <!-- Used for fixing robot to Gazebo 'base_link' -->
    <link name="world"/>

    <!-- Base Link -->
    <link name="sensor_link">
        <collision>
            <origin xyz="-${stereo_z/2} 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${stereo_x} ${stereo_y} ${stereo_z}"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="-${stereo_x/2} 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${stereo_x} ${stereo_y} ${stereo_z}"/>
            </geometry>
            <material name="orange"/>
        </visual>

        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="1"/>
            <inertia
                ixx="1.0" ixy="0.0" ixz="0.0"
                iyy="1.0" iyz="0.0"
                izz="1.0"/>
        </inertial>
    </link>

    <joint name="sensor_joint" type="fixed">
        <parent link="world"/>
        <child link="sensor_link"/>
        <origin xyz="0 0 ${object_height}" rpy="0 0 0" /> 
        <!-- 0.75 0.035 0.5 -->
    </joint>

    <material name="orange">
        <color rgba="${255/255} ${108/255} ${10/255} 1.0"/>
    </material>

    <gazebo reference="sensor_link">
        <material>Gazebo/Black</material>
    </gazebo>

</robot>
