darknet_ros_topic: /darknet_ros/bounding_boxes_nms/
output_bbx3d_topic: /darknet_ros_3d/bounding_boxes
# point_cloud_topic: /camera/depth_registered/points
# working_frame: camera_link
point_cloud_topic: /stereo_camera/points2
working_frame: stereo_camera2_link
# working_frame: world
mininum_detection_thereshold: 0.3
minimum_probability: 0.3
interested_classes: ["aeroplane", "person", "italian_biscotti", "smoothie", "mango_juice", "crisps", "water", "sandwich", "toastie", "veggie_pot", "wrap", "espresso", "cappuccino", "americano"]
