in_cloud_topic: /stereo_camera/points2 # point_cloud_topic: /camera/depth_registered/points
lidar_frame_id: stereo_camera2_link #working_frame: stereo_camera2_link


# ======== other of bbox ===========#
# bbox2d_topic: /darknet_ros/bounding_boxes
# output_bbx3d_topic: /darknet_ros_3d/bounding_boxes
# depth_image_topic: /velodyne_depth_image
# marker_array_topic: /bbox3d_marker_array
# cloud_z_thresh: 0.0
# out_cloud_topic: /bbox_cloud

# =========== other of darknet_ros_3d ===========#
# mininum_detection_thereshold: 0.3
# minimum_probability: 0.3
# interested_classes: ["aeroplane", "person", "italian_biscotti", "smoothie", "mango_juice", "crisps", "water", "sandwich", "toastie", "veggie_pot", "wrap", "espresso", "cappuccino", "americano"]
